apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- client-deployment.yaml
- server-deployment.yaml
- mongodb-deployment.yaml
- client-service.yaml
- server-service.yaml
- mongodb-service.yaml
- env-configmap.yaml
namespace: mern-green
images:
- name: backend-hw3
  newName: opozden/backend-hw3
  newTag: 339c7145294459a86a33423fb076e2b68becf53f
- name: frontend-hw3
  newName: opozden/frontend-hw3
  newTag: 339c7145294459a86a33423fb076e2b68becf53f
