apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: server
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: mongodb
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_DATABASE
                  name: env
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_DOCKER_PORT
                  name: env
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGODB_PASSWORD
                  name: mern-secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: MONGODB_USER
                  name: mern-secret
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  key: CLOUDINARY_CLOUD_NAME
                  name: mern-secret
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  key: CLOUDINARY_API_KEY
                  name: mern-secret
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  key: CLOUDINARY_API_SECRET
                  name: mern-secret
          image: opozden/backend-mern:prod
          name: backend
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
